language: csharp
dist: trusty
mono: none
dotnet: 2.1
install:
- dotnet restore
script:
- dotnet build
- dotnet test ./Tests/Tests.Unit/Tests.Unit.csproj
- dotnet test ./Tests/Tests.Integration/Tests.Integration.csproj
