language: csharp
dist: trusty
mono: none
dotnet: 2.2.100
install:
- dotnet restore
script:
- dotnet build
- dotnet test test/Tests.Unit/Tests.Unit.csproj
#- dotnet test test/Tests.Integration/Tests.Integration.csproj
